### ISSUE TITLE
Heading level changes on step 2

### ISSUE THREAD

**Issue by Paining1** [slnsys/obsidian-canvas2document#11]
Hello, I love your plugin. 

When I go from step 1 to step 2, the notes I connected to another note (who became second level headers in step 1) revert back to header level 1. Is this normal?

**Comment by Paining1** [comment]
ah I think I know whats going on, if we embed a note, can you make it ignore its title, i think this is getting in the way of the hierarchy

**Comment by Paining1** [comment]
ah it seems theres a difference between cards, and note file. If possible can you just treat note file the same way as cards, or at least have an option

**Comment by slnsys** [comment]
Hi,
thany you for clarifying this issue. It's something that needs to get covered in more detail in the documentation. And some parts need to get options in next releases.

The point is, that Canvas2Document needs to cover the maps landscape as far as possible, which is reading the canvas' hierarchy information. That way you can reorder and optimize the order of everything that's implemented in the canvas. From notefiles only the (nonhierarchical) filename is used to identify the object.
So, this map
![image](https://github.com/user-attachments/assets/9e617636-8bfc-4453-a90f-cfccd8e9af70)

has this outline:
![image](https://github.com/user-attachments/assets/4a353e31-1a4a-499c-917a-e4cc743be24f)

In the second step, the addon's "navigational headers" for reordering are removed and the pure content with structure information (headings) are used. And so, there is the level 1 heading in the notefile's title.
And we end up with the final document with it's outline showing all things in order:
![image](https://github.com/user-attachments/assets/7033427b-3ec0-46ab-bdda-43a6e8d7e514)
