### ISSUE TITLE
Excalidraw integration?

### ISSUE THREAD

**Issue by Paining1** [slnsys/obsidian-canvas2document#12]
Will you ever make it work for excalidraw?

**Comment by slnsys** [comment]
You mean embedding drawings in resulting documents like they were embedded in a canvas?
Or maybe converting an excalidraw drawing like a canvas and making a document out of it?

**Comment by Paining1** [comment]
Converting an excalidraw drawing into a document

**Comment by Paining1** [comment]
Excalidraw is much faster than canvas, and has more functionality. And they even have elbow arrows now. Perhaps that could be the way to set heiracy?

**Comment by slnsys** [comment]
sorry, but it can't simply get transferred to handling Excalidraw. This would be something completely different.

**Comment by slnsys** [comment]
close
