### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ronilaukkarinen** [slnsys/obsidian-canvas2document#14]
When I select Canvas2document (either step) from the command prompt, nothing happens.

**Comment by slnsys** [comment]
You have loaded a canvas file and there is no notification (in the top right corner of Obsidian)?

If so, could you please send me a screenshot of obsidian's developer console (to open with Ctrl-Shift-I) after the problem occured?



Thank you!

**Comment by ronilaukkarinen** [comment]
<img width="1827" alt="image" src="https://github.com/user-attachments/assets/262e01b6-4bc0-4742-9b01-5f010e61b8c7">

**Comment by sharetocreate** [comment]
Im getting the same, though it did work with the first canvas i loaded. The last two though nothing happens - 

Says this in the developer log issues (see attached
![Uploading Screenshot 2024-10-26 at 19.16.53.jpg…]()
)
plugin:canvas2document:344 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '3')
    at Canvas2DocumentPlugin.writeCanvDocFile (plugin:canvas2document:344:34)
    at Object.callback (plugin:canvas2document:59:35)

**Comment by slnsys** [comment]
This look a lot like an error from 1.2.1. Do you have the latest version 1.2.2?

**Comment by sharetocreate** [comment]
> This look a lot like an error from 1.2.1. Do you have the latest version 1.2.2?

I do - recently installed

Just did another test with a different canvas and that worked fine - so I think maybe the error with the others, was that they contain embedded canvas' which is fine to workaround if that causes issue with transfer to document

**Comment by slnsys** [comment]
Ok, I will check that. Embedded canvas is something that should get supported in one of the next releases, anyway.

**Comment by slnsys** [comment]
confirmed, that crashes on embedded canvas under some circumstances, needs a fix release

**Comment by slnsys** [comment]
released with 1.2.3

**Comment by sharetocreate** [comment]
Great work. Thanks @sinsys

> released with 1.2.3

**Comment by slnsys** [comment]
thank you! ID is @slnsys :-)
