### ISSUE TITLE
Option to retain headings to add structure to output document

### ISSUE THREAD

**Issue by AW2307** [slnsys/obsidian-canvas2document#4]
Hi,

this plugin is almost exactly what I have been looking for and fills an important gap.

What's missing to fully address my use case is an option to retain the headings of markdown documents that were added to the canvas.

Ideally, these headings would actually be displayed in the outline after first creating a document with canvas2document. This would make arranging the sections easier than with the current repeating placeholder "___noteFile from Canvas". Same for the "___card from Canvas" placeholder, ideally the first 5-10 words of the card would be displayed here.

To get to the main point of my request though: After clearing the document in step 2, I'd like the headings of the included markdown documents to be retained. Currently, they are completely removed.

Maybe there could be a global preference in the plugin settings for enabling or disabling this, or a dialogue to decide each time.

Thanks for considering.

**Comment by slnsys** [comment]
Hi, thank you for your feedback and for using the plugin. The **requirement for "named" navigational headings** is coming within the next few days. Only needs code clearing.

The **internal content headings should not get removed**. Attached a screencast with the canvas and the documents of the two steps. Please see the outline panel on the right: step 1: navigational headings (coming soon with implied titles). step 2: just everything in original structure. Maybe you can send me your canvas file (or an abstracted version of it...)?

![headingsconservation](https://github.com/slnsys/obsidian-canvas2document/assets/161649412/2a1be9c1-06ef-4d42-96d1-409fd31c6bfd)

_This screencast also already contains the hierarchically parsed canvas elements. Coming also in the next few days._

**Comment by AW2307** [comment]
That looks awesome! Very much looking forward to trying this once available.

I think the headings not being retained is because I'm using embedded markdown documents in the canvas, whereas in the above example you are using cards. If I add a heading to a card, then this heading is indeed retained in the final document output.

However, what I'm requesting is that for a markdown document embedded in the canvas, the final document should include the title of the markdown document. Currently, titles of markdown documents are ignored and only the contents are retained.

To make this more concrete: In the following canvas structure I'd like the markdown document's title to ideally be included in the final document as a ### heading.
1. Card1
2. Card2
2.1 Card2a
2.1.1 Markdown Document
2.2 Card2b

Does this make sense from your perspective?

The markdown title behavior is consistent over here, so it should be easily reproducible. Please try adding a markdown document to a canvas via "add note from vault", run canvas2document and verify the title not being included.

If it would still be helpful to share a canvas, let me know and I will do so.

Cheers

**Comment by slnsys** [comment]
ok, thank you, now i got it. What you are missing as the main heading is actually the md file name. All the headings '###...' of the embedded files go into the converted document 1:1.

But what you're talking about is absolutely a valid requirement. The descriptive filename should definitely be the main heading above this segment, as it is in the canvas.

This will go into the settings or a options dialog of the current conversion.
Thank you!

**Comment by AW2307** [comment]
Glad to hear it! Keep up the great work.

**Comment by slnsys** [comment]
is done in Release 1.2.0
