### ISSUE TITLE
Convert .MD file Not Created

### ISSUE THREAD

**Issue by kennygokh** [slnsys/obsidian-canvas2document#8]
Hi, I have run the command of step 1 to convert a canvas file. I can see a folder name is created but there is no files inside the folders as described in the documents mentioned. <img width="899" alt="image" src="https://github.com/user-attachments/assets/acb4eb39-8b75-46f0-8146-cab08d4c3b76">

When I continue to step 2, it gave a message "this is not a Convert2Document target file". 

In developer console, I found an error. 
<img width="534" alt="image" src="https://github.com/user-attachments/assets/8e308a93-2aa7-4316-99f6-2ab109e0a3fb">

Please advise what is the cause of the issue.

**Comment by slnsys** [comment]
sorry for late answer, holiday season...

This is normal behavior. A conversion process creates the working directory, but this is only needed for cards (canvas elements that only exist in the canvas) that are converted into MD files during the conversion. If the canvas only contains existing files (MD, images, ...), the working directory remains empty.
And when you trigger the second conversion step, the output file from step 1 (..._fromCanvas.md) must be focused.

**Comment by kennygokh** [comment]
Hi @slnsys, noted the comment on step 1 however in step 2, i could not find any file that is (..._fromCanvas.md). I assume (..._fromCanvas.md) is the converted file from my original file? eg my file name is mycanvas.canvas and it will become mycanvas_fromCanvas.md. Is that correct?

**Comment by slnsys** [comment]
yes, that's correct. The screenshot shows a initial canvas, the temp-dir and the files for step 1 and step 2
![image](https://github.com/user-attachments/assets/dfdd9180-0e5e-4e22-957f-efeb7a65b8d2)

**Comment by slnsys** [comment]
But I still can't reproduce the error from the dev console, which suggests a different error. Is it possible for you to send me the canvas so I can recreate it?

**Comment by slnsys** [comment]
This got a new release, check https://github.com/slnsys/obsidian-canvas2document/releases/tag/1.2.2
Thank you very much for providing the data and for the detailed error message.

**Comment by kennygokh** [comment]
I have updated the latest updates. It is working now. Thanks @slnsys
